export const GET_HEATMAP_SUCCESS = 'GET_HEATMAP_SUCCESS';
export const GET_BOUND_LOCATIONS_SUCCESS = 'GET_BOUND_LOCATIONS_SUCCESS';
export const GET_BOUND_USERS_SUCCESS = 'GET_BOUND_USERS_SUCCESS';
export const GET_LOCATION_CHECKINS = 'GET_LOCATION_CHECKINS';