export const GET_HEATMAP_SUCCESS = 'GET_HEATMAP_SUCCESS';
export const SAVE_CHECKIN_GROUPS = 'SAVE_CHECKIN_GROUPS';
export const GET_EDGES_SUCCESS = 'GET_EDGES_SUCCESS';
export const GET_USERS_CHECKIN_TOTAL_SUCCESS = 'GET_USERS_CHECKIN_TOTAL_SUCCESS';

export const GET_HOTSPOTS_SUCCESS = 'GET_HOTSPOTS_SUCCESS';
export const GET_LOCATION_CHECKINS = 'GET_LOCATION_CHECKINS';


export const GET_BOUND_LOCATIONS_SUCCESS = 'GET_BOUND_LOCATIONS_SUCCESS';
export const GET_BOUND_USERS_SUCCESS = 'GET_BOUND_USERS_SUCCESS';