export const RECEIVE_EDGE_SUCCESS = 'RECEIVE_EDGE_SUCCESS';
export const GET_BOUND_LOCATIONS_SUCCESS = 'GET_BOUND_LOCATIONS_SUCCESS';
export const GET_BOUND_USERS_SUCCESS = 'GET_BOUND_USERS_SUCCESS';
export const GET_LOCATION_CHECKINS = 'GET_LOCATION_CHECKINS';